spring:
  application:
    name: chatroomws
  data:
    mongodb:
      username: aadi
      password: aadi
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin  

